### ISSUE TITLE
error in Debian 10 with default example

### ISSUE THREAD

**Issue by ackierhys** [giveabit/TrioWaveCutter#1]
I installed the statistics module on debian 10 (buster) with apt-get install python-statistics Version: 3.4.0b3-2
(python-statistics - Python 2.* port of 3.4 Statistics Module (Python 2)):

Then I ran

```
a@m1:~/Downloads/TrioWaveCutter-master$ cp example/example.wav .
a@m1:~/Downloads/TrioWaveCutter-master$  python TrioWaveCutter_v1.1_linux.py example.wav 
-----------------------------------------------------------------------------
|                                                                    @@     |
|                                                                    @@     |
|                                                                 @@@@@@@@  |
|                                                                    @@     |
| @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@     @@@      @@@@@@@@@@@@@       @@     |
|        @@@         @@@         @@@    @@@    @@@@          @@@            |
|        @@@         @@@          @@@   @@@   @@@             @@@@          |
|        @@@         @@@          @@@   @@@  @@@@              @@@          |
|        @@@         @@@        @@@@    @@@  @@@               @@@@         |
|        @@@         @@@@@@@@@@@@@      @@@  @@@                @@@         |
|        @@@         @@@    @@@@        @@@  @@@               @@@          |
|        @@@         @@@      @@@       @@@   @@@              @@@          |
|        @@@         @@@       @@@      @@@   @@@@            @@@           |
|        @@@         @@@        @@@@    @@@     @@@@       @@@@@            |
|        @@@         @@@          @@@   @@@        @@@@@@@@@@               |
-----------------------------------------------------------------------------
WAVE CUTTING TOOL - giveabit@mail.ru



processing: example.wav


			[x] gathering noise floor.Traceback (most recent call last):
  File "TrioWaveCutter_v1.1_linux.py", line 352, in <module>
    meanFloor, stdFloor = meanLoudness(data, start, end)
  File "TrioWaveCutter_v1.1_linux.py", line 142, in meanLoudness
    val = int.from_bytes(temp, byteorder='little', signed=True)
AttributeError: type object 'int' has no attribute 'from_bytes'

```

For 1.0 I get:

```
a@m1:~/Downloads/TrioWaveCutter-master$ python TrioWaveCutter_v1.0_linux.py example.wav 
-----------------------------------------------------------------------------
|                                                                    @@     |
|                                                                    @@     |
|                                                                 @@@@@@@@  |
|                                                                    @@     |
| @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@     @@@      @@@@@@@@@@@@@       @@     |
|        @@@         @@@         @@@    @@@    @@@@          @@@            |
|        @@@         @@@          @@@   @@@   @@@             @@@@          |
|        @@@         @@@          @@@   @@@  @@@@              @@@          |
|        @@@         @@@        @@@@    @@@  @@@               @@@@         |
|        @@@         @@@@@@@@@@@@@      @@@  @@@                @@@         |
|        @@@         @@@    @@@@        @@@  @@@               @@@          |
|        @@@         @@@      @@@       @@@   @@@              @@@          |
|        @@@         @@@       @@@      @@@   @@@@            @@@           |
|        @@@         @@@        @@@@    @@@     @@@@       @@@@@            |
|        @@@         @@@          @@@   @@@        @@@@@@@@@@               |
-----------------------------------------------------------------------------
WAVE CUTTING TOOL - giveabit@mail.ru



processing: example.wav

What instruments have you recorded?
You can input [g] for guitar, [b] for bass and [d] for drums.

Please input the instruments in the order that they were recorded.
If you enter nothing, 'gbd' will be selected as default.


Your instruments are: 
Traceback (most recent call last):
  File "TrioWaveCutter_v1.0_linux.py", line 315, in <module>
    userArgs = userArgsHandling()
  File "TrioWaveCutter_v1.0_linux.py", line 271, in userArgsHandling
    instruments = input('Your instruments are: ')
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing


```

**Comment by ackierhys** [comment]
Fixed. Needed to run with python3
